after composer update throw
Exception: Class pushNotification does not exist
Skipping \Davibennun\LaravelPushNotification\Facades\PushNotification.

change pushNotification to PushNotification
fixed class name in PushNotification.php